services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn api_server:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app_network

  script_executor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 