services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./logs:/app/logs
      - ./certs:/certs
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python -m api_server
    networks:
      - app_network

  script_executor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 